# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e65aa29814db65a405e12ea13daa27d2225d324d693b63d2e1e1a703596bf35cf2fa6c5f7268aa8392f21595321e1159fc7e3ecab1663b8124e3e1607408b8

test:
  secret_key_base: 21bbfb2a7c3bc8b9588c11abae963fc489427ac586e5f1e7caff69a23eb25905701ca713bc1f1f8af88cd597780ab864b7601485c7afd6e6f2f370f31fddcce1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
